import React from "react";
import { Heading, List, Paragraph, Strong } from "@dynatrace/strato-components/typography";

export const HowItWorks = () => (
  <div className="ff-about">
    <Heading level={2}>How it works</Heading>
    <Paragraph>
      <Strong>Multi-lane Free Flow</Strong> shows a multi-lane free-flow toll gantry in motion, from the vehicle passing under the gantry to the settled
      charge. It is a <Strong>demonstration</Strong>: the data is generated by a simulator running in your browser, for a fictitious operator. Nothing
      is read from or written to your Dynatrace environment, and the app requests no data permissions.
    </Paragraph>

    <Heading level={4}>What is simulated</Heading>
    <List>
      <li>Every vehicle in the scene is one simulated transaction: vehicle class, tag, plate read, tariff and charge.</li>
      <li>Volume follows a typical weekday curve in your local time, with peaks at 8 am and 6 pm.</li>
      <li>Plates are fictitious; masking hides only the last two digits.</li>
      <li>Dynatrace Intelligence analyses are scripted for each scenario.</li>
      <li>During incidents, the totals (queues, revenue, duration) run 100× faster than the clock so they fit in a demo.</li>
    </List>

    <Heading level={4}>Baseline numbers</Heading>
    <Paragraph>
      Around 56,000 transactions on a weekday, a class 1 tariff of $4.50, 77% of transactions with a tag, plaza health of 94 (the OCR GPU is
      heating up), 98.4% automatic identification, 98.5% OCR confidence and a p95 of about 12 s from passage to settled charge.
    </Paragraph>

    <Heading level={4}>What changes with real data</Heading>
    <List>
      <li>Transactions and charges: Business Events sent by the lane controller via OpenPipeline, with the plate masked at ingest.</li>
      <li>Gantry equipment: Extensions (SNMP or vendor API) and lane controller logs.</li>
      <li>Edge data center: OneAgent on hosts, with GPU, storage and UPS extensions.</li>
      <li>Services and transaction journey: Distributed Tracing (OneAgent / OpenTelemetry).</li>
      <li>Queues: the extension for the operator&apos;s message broker.</li>
      <li>Partners: traces of outbound calls and Synthetic monitors on the APIs.</li>
      <li>Problems, root cause and forecasts: Dynatrace Intelligence.</li>
    </List>
    <Paragraph>
      The <Strong>Data &amp; integrations</Strong> tab lists every field and metric to connect.
    </Paragraph>

    <Heading level={4}>Shortcuts</Heading>
    <Paragraph>
      0 normal · 1 holiday exodus · 2 fog · 3 IR illuminator · 4 tag issuer · 5 fiber · 6 GPU · Space pause · + / − speed · M mask · D sources · T TV
      mode · R summary · P presenter · I Dynatrace Intelligence.
    </Paragraph>
  </div>
);
